#!/usr/bin/env bash
set -e

# ==============================================================================
# Unified Document Viewer — Automatic Zero-Config Startup Script
# Automatically detects port conflicts, finds free ports, starts Docker & App
# ==============================================================================

# Helper: Check if a port is in use
is_port_in_use() {
    local port=$1
    if command -v lsof >/dev/null 2>&1; then
        lsof -i ":${port}" -sTCP:LISTEN -t >/dev/null 2>&1
    elif command -v nc >/dev/null 2>&1; then
        nc -z localhost "${port}" >/dev/null 2>&1
    else
        return 1
    fi
}

# Helper: Find the next available port starting from a preferred port
find_free_port() {
    local preferred=$1
    local port=$preferred
    local container_name=$2

    # If the port is used by our own container, we can reuse it
    if [ -n "$container_name" ] && docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${container_name}$"; then
        echo "$port"
        return 0
    fi

    while is_port_in_use "$port"; do
        port=$((port + 1))
    done
    echo "$port"
}

echo "========================================================================"
echo " 🚀 Starting Unified Document Viewer (Zero-Config Auto Port Allocation)"
echo "========================================================================"

# 1. Resolve Available Ports Automatically
echo "[1/4] Checking ports and resolving conflicts automatically..."
RESOLVED_DB_PORT=$(find_free_port 5432 "docviewer-postgres")
RESOLVED_IDP_PORT=$(find_free_port 8088 "docviewer-idp-mock")
RESOLVED_SALES_PORT=$(find_free_port 8081 "docviewer-sales-stub")
RESOLVED_SERVICE_PORT=$(find_free_port 8082 "docviewer-service-stub")

# If port 8080 is in use, find next available port (e.g. 8085, 8086...)
if is_port_in_use 8080 && ! (curl -s -m 1 "http://localhost:8080/actuator/health" 2>/dev/null | grep -q '"status":"UP"'); then
    RESOLVED_APP_PORT=$(find_free_port 8085)
else
    RESOLVED_APP_PORT=8080
fi

# 2. Persist resolved ports to .env for all subsequent commands
cat <<EOF > .env
# Auto-generated by start-app.sh
APP_PORT=${RESOLVED_APP_PORT}
PORT=${RESOLVED_APP_PORT}
DB_PORT=${RESOLVED_DB_PORT}
SALES_PORT=${RESOLVED_SALES_PORT}
SERVICE_PORT=${RESOLVED_SERVICE_PORT}
IDP_PORT=${RESOLVED_IDP_PORT}
EOF

echo " -> Allocated Ports:"
echo "    • App Port      : ${RESOLVED_APP_PORT}"
echo "    • Database Port : ${RESOLVED_DB_PORT}"
echo "    • Sales Stub    : ${RESOLVED_SALES_PORT}"
echo "    • Service Stub  : ${RESOLVED_SERVICE_PORT}"
echo "    • IdP Mock      : ${RESOLVED_IDP_PORT}"

# 3. Start Docker Infrastructure
echo "[2/4] Starting Docker backing services (PostgreSQL, Stubs, IdP)..."
docker compose up -d postgres sales-stub service-stub idp-mock

# Wait briefly for database to be healthy
echo " -> Waiting for database readiness..."
for i in {1..15}; do
    if docker exec docviewer-postgres pg_isready -U docuser -d docviewer >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

# 4. Build if JAR does not exist
if [ ! -f "target/unifieddocviewer-0.0.1-SNAPSHOT.jar" ]; then
    echo "[3/4] Building JAR with Maven..."
    mvn clean package -DskipTests
else
    echo "[3/4] Executable JAR found: target/unifieddocviewer-0.0.1-SNAPSHOT.jar"
fi

# 5. Launch Spring Boot Application (if not already running on target port)
echo "[4/4] Starting Unified Document Viewer on port ${RESOLVED_APP_PORT}..."

if curl -s -m 1 "http://localhost:${RESOLVED_APP_PORT}/actuator/health" | grep -q '"status":"UP"'; then
    echo " -> Application is already running and UP on port ${RESOLVED_APP_PORT}."
else
    # Launch in background
    nohup java -Dserver.port="${RESOLVED_APP_PORT}" \
         -Dspring.datasource.url="jdbc:postgresql://localhost:${RESOLVED_DB_PORT}/docviewer" \
         -Dexternal-systems.systems.sales.base-url="http://localhost:${RESOLVED_SALES_PORT}" \
         -Dexternal-systems.systems.sales.token-uri="http://localhost:${RESOLVED_IDP_PORT}/token" \
         -Dexternal-systems.systems.service.base-url="http://localhost:${RESOLVED_SERVICE_PORT}" \
         -Dexternal-systems.systems.service.token-uri="http://localhost:${RESOLVED_IDP_PORT}/token" \
         -Dspring.security.oauth2.resourceserver.jwt.issuer-uri="http://localhost:${RESOLVED_IDP_PORT}/realms/dealership" \
         -Dspring.security.oauth2.resourceserver.jwt.jwk-set-uri="http://localhost:${RESOLVED_IDP_PORT}/realms/dealership/protocol/openid-connect/certs" \
         -jar target/unifieddocviewer-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
    
    APP_PID=$!
    echo " -> Launched Spring Boot PID ${APP_PID}. Waiting for health check..."

    # Poll Actuator health endpoint
    READY=false
    for i in {1..30}; do
        if curl -s -m 1 "http://localhost:${RESOLVED_APP_PORT}/actuator/health" 2>/dev/null | grep -q '"status":"UP"'; then
            READY=true
            break
        fi
        sleep 1
    done

    if [ "$READY" = true ]; then
        echo " -> Application started successfully!"
    else
        echo " -> Application startup timed out. Check app.log for details."
        exit 1
    fi
fi

echo "========================================================================"
echo " ✅ Application is READY to use!"
echo " • Swagger UI  : http://localhost:${RESOLVED_APP_PORT}/swagger-ui.html"
echo " • API Docs    : http://localhost:${RESOLVED_APP_PORT}/v3/api-docs"
echo " • Health      : http://localhost:${RESOLVED_APP_PORT}/actuator/health"
echo " • Test Runner : ./scripts/test-runner.sh demo"
echo "========================================================================"
