#!/usr/bin/env bash
set -e

# ==============================================================================
# Unified Document Viewer — Automatic Zero-Config Startup Script
# Automatically detects port conflicts, finds free ports, starts Docker & App
# ==============================================================================

# Helper: Check if a port is in use
is_port_in_use() {
    local port=$1
    if command -v lsof >/dev/null 2>&1; then
        lsof -i ":${port}" -sTCP:LISTEN -t >/dev/null 2>&1
    elif command -v nc >/dev/null 2>&1; then
        nc -z localhost "${port}" >/dev/null 2>&1
    else
        return 1
    fi
}

# Helper: Find the next available port starting from a preferred port
find_free_port() {
    local preferred=$1
    local port=$preferred
    local container_name=$2

    # If the port is used by our own container, we can reuse it
    if [ -n "$container_name" ] && docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${container_name}$"; then
        echo "$port"
        return 0
    fi

    while is_port_in_use "$port"; do
        port=$((port + 1))
    done
    echo "$port"
}

echo "========================================================================"
echo " 🚀 Starting Unified Document Viewer (Zero-Config Auto Port Allocation)"
echo "========================================================================"

# 1. Resolve Available Ports Automatically
echo "[1/4] Checking ports and resolving conflicts automatically..."
RESOLVED_DB_PORT=$(find_free_port 5432 "docviewer-postgres")
RESOLVED_IDP_PORT=$(find_free_port 8088 "docviewer-idp-mock")
RESOLVED_SALES_PORT=$(find_free_port 8081 "docviewer-sales-stub")
RESOLVED_SERVICE_PORT=$(find_free_port 8082 "docviewer-service-stub")

# Resolve App Port, ensuring no conflict with assigned stubs
RESOLVED_APP_PORT=8080
while is_port_in_use "$RESOLVED_APP_PORT" || [ "$RESOLVED_APP_PORT" = "$RESOLVED_IDP_PORT" ] || [ "$RESOLVED_APP_PORT" = "$RESOLVED_SALES_PORT" ] || [ "$RESOLVED_APP_PORT" = "$RESOLVED_SERVICE_PORT" ]; do
    RESOLVED_APP_PORT=$((RESOLVED_APP_PORT + 1))
done

# 2. Persist resolved ports to .env for all subsequent commands
cat <<EOF > .env
# Auto-generated by start-app.sh
APP_PORT=${RESOLVED_APP_PORT}
PORT=${RESOLVED_APP_PORT}
DB_PORT=${RESOLVED_DB_PORT}
SALES_PORT=${RESOLVED_SALES_PORT}
SERVICE_PORT=${RESOLVED_SERVICE_PORT}
IDP_PORT=${RESOLVED_IDP_PORT}
EOF

echo " -> Allocated Ports:"
echo "    • App Port      : ${RESOLVED_APP_PORT}"
echo "    • Database Port : ${RESOLVED_DB_PORT}"
echo "    • Sales Stub    : ${RESOLVED_SALES_PORT}"
echo "    • Service Stub  : ${RESOLVED_SERVICE_PORT}"
echo "    • IdP Mock      : ${RESOLVED_IDP_PORT}"

# 3. Stop any host-level Java app process if lingering
if is_port_in_use "${RESOLVED_APP_PORT}"; then
    echo " -> Freeing port ${RESOLVED_APP_PORT} from local process..."
    lsof -ti ":${RESOLVED_APP_PORT}" | xargs kill -9 2>/dev/null || true
fi

# 4. Build fresh JAR if needed
if [ ! -f "target/unifieddocviewer-0.0.1-SNAPSHOT.jar" ]; then
    echo "[2/3] Building JAR with Maven..."
    mvn clean package -DskipTests
fi

# 5. Start Entire Stack in Docker (PostgreSQL, Stubs, IdP, and App Container)
echo "[2/3] Building and starting all Docker services (App, PostgreSQL, Stubs, IdP)..."
docker compose up -d --build

# 5. Wait for App Health Check
echo "[3/3] Waiting for Unified Document Viewer container to become healthy on port ${RESOLVED_APP_PORT}..."
READY=false
for i in {1..40}; do
    if curl -s -m 1 "http://localhost:${RESOLVED_APP_PORT}/actuator/health" 2>/dev/null | grep -q '"status":"UP"'; then
        READY=true
        break
    fi
    sleep 1
done

if [ "$READY" = true ]; then
    echo " -> Container docviewer-app is UP and healthy!"
else
    echo " -> Application startup timed out. Container logs:"
    docker logs docviewer-app --tail 30 || true
    exit 1
fi

echo "========================================================================"
echo " ✅ Application is RUNNING IN DOCKER and ready to use!"
echo " • Container   : docviewer-app"
echo " • Swagger UI  : http://localhost:${RESOLVED_APP_PORT}/swagger-ui.html"
echo " • API Docs    : http://localhost:${RESOLVED_APP_PORT}/v3/api-docs"
echo " • Health      : http://localhost:${RESOLVED_APP_PORT}/actuator/health"
echo " • Test Runner : ./scripts/test-runner.sh demo"
echo "========================================================================"
